defmodule Slouch.Repo.Migrations.AddBots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :is_bot, :boolean, null: false, default: false
    end

    create table(:bots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :handler_module, :text, null: false
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "bots_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:bots, [:name], name: "bots_unique_name_index")

    create unique_index(:bots, [:user_id], name: "bots_unique_user_index")
  end

  def down do
    drop_if_exists unique_index(:bots, [:user_id], name: "bots_unique_user_index")

    drop_if_exists unique_index(:bots, [:name], name: "bots_unique_name_index")

    drop constraint(:bots, "bots_user_id_fkey")

    drop table(:bots)

    alter table(:users) do
      remove :is_bot
    end
  end
end
