defmodule Slouch.Repo.Migrations.AddReactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :emoji, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :message_id,
          references(:messages,
            column: :id,
            name: "reactions_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "reactions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:reactions, [:message_id, :user_id, :emoji],
             name: "reactions_unique_reaction_index"
           )
  end

  def down do
    drop_if_exists unique_index(:reactions, [:message_id, :user_id, :emoji],
                     name: "reactions_unique_reaction_index"
                   )

    drop constraint(:reactions, "reactions_message_id_fkey")

    drop constraint(:reactions, "reactions_user_id_fkey")

    drop table(:reactions)
  end
end
