defmodule Slouch.Repo.Migrations.FixDmFeatures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:dm_reactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :emoji, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :direct_message_id,
          references(:direct_messages,
            column: :id,
            name: "dm_reactions_direct_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "dm_reactions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:dm_reactions, [:direct_message_id, :user_id, :emoji],
             name: "dm_reactions_unique_dm_reaction_index"
           )

    alter table(:direct_messages) do
      add :parent_message_id,
          references(:direct_messages,
            column: :id,
            name: "direct_messages_parent_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:direct_messages, "direct_messages_parent_message_id_fkey")

    alter table(:direct_messages) do
      remove :parent_message_id
    end

    drop_if_exists unique_index(:dm_reactions, [:direct_message_id, :user_id, :emoji],
                     name: "dm_reactions_unique_dm_reaction_index"
                   )

    drop constraint(:dm_reactions, "dm_reactions_direct_message_id_fkey")

    drop constraint(:dm_reactions, "dm_reactions_user_id_fkey")

    drop table(:dm_reactions)
  end
end
