defmodule Slouch.Repo.Migrations.AddConfirmationAddon do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # All changes were already applied by the create_chat_resources migration
  end

  def down do
    # No-op
  end
end
