defmodule Slouch.Repo.Migrations.CreateChatResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :confirmed_at, :utc_datetime_usec
    end

    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :channel_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :channel_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create table(:channels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:messages) do
      modify :channel_id,
             references(:channels,
               column: :id,
               name: "messages_channel_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "messages_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:memberships) do
      modify :channel_id,
             references(:channels,
               column: :id,
               name: "memberships_channel_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "memberships_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:memberships, [:channel_id, :user_id],
             name: "memberships_unique_membership_index"
           )

    alter table(:channels) do
      add :name, :text, null: false
      add :topic, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:channels, [:name], name: "channels_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:channels, [:name], name: "channels_unique_name_index")

    alter table(:channels) do
      remove :updated_at
      remove :inserted_at
      remove :topic
      remove :name
    end

    drop_if_exists unique_index(:memberships, [:channel_id, :user_id],
                     name: "memberships_unique_membership_index"
                   )

    drop constraint(:memberships, "memberships_channel_id_fkey")

    drop constraint(:memberships, "memberships_user_id_fkey")

    alter table(:memberships) do
      modify :user_id, :uuid
      modify :channel_id, :uuid
    end

    drop constraint(:messages, "messages_channel_id_fkey")

    drop constraint(:messages, "messages_user_id_fkey")

    alter table(:messages) do
      modify :user_id, :uuid
      modify :channel_id, :uuid
    end

    drop table(:channels)

    drop table(:memberships)

    drop table(:messages)

    alter table(:users) do
      remove :confirmed_at
    end
  end
end
