defmodule Slouch.Repo.Migrations.AddDirectMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:direct_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:direct_messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "direct_messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "direct_messages_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:conversations) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:conversation_participants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_participants_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "conversation_participants_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:conversation_participants, [:conversation_id, :user_id],
             name: "conversation_participants_unique_participant_index"
           )
  end

  def down do
    drop_if_exists unique_index(:conversation_participants, [:conversation_id, :user_id],
                     name: "conversation_participants_unique_participant_index"
                   )

    drop constraint(:conversation_participants, "conversation_participants_conversation_id_fkey")

    drop constraint(:conversation_participants, "conversation_participants_user_id_fkey")

    drop table(:conversation_participants)

    alter table(:conversations) do
      remove :updated_at
      remove :inserted_at
    end

    drop constraint(:direct_messages, "direct_messages_conversation_id_fkey")

    drop constraint(:direct_messages, "direct_messages_user_id_fkey")

    alter table(:direct_messages) do
      modify :user_id, :uuid
      modify :conversation_id, :uuid
    end

    drop table(:conversations)

    drop table(:direct_messages)
  end
end
