defmodule Slouch.Repo.Migrations.AddMessageThreads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :parent_message_id,
          references(:messages,
            column: :id,
            name: "messages_parent_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:messages, "messages_parent_message_id_fkey")

    alter table(:messages) do
      remove :parent_message_id
    end
  end
end
